[package]
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = ""
edition = "2018"
repository = "https://codeberg.org/morph/morph"
readme = "README.md"
name = "morph"
version = "0.1.0"
keywords = [
    "embedded",
    "no_std",
    "ui",
]

[lib]
name = "morph"
path = "src/lib.rs"
test = false

[target.thumbv7m-none-eabi.dependencies]
cortex-m = "0.6.2"
cortex-m-rt = "0.6.12"
cortex-m-semihosting = "0.3.5"
panic-halt = "0.2.0"

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = { version = "0.4.5", optional = true }
web-sys = { version = "0.3.35", features = ["Console", "Window"] }

[features]
default = []
no_std = []

[target.wasm32-unknown-unknown.features]
default = ["console_error_panic_hook"]