[package]
authors = ["Florian Blasius <flovanpt@posteo.de>"]
description = ""
edition = "2018"
repository = "https://codeberg.org/morph/morph"
readme = "README.md"
name = "morph"
version = "0.1.0"
keywords = [
    "embedded",
    "no_std",
    "ui",
]

[target.thumbv7m-none-eabi.dev-dependencies]
cortex-m = "0.6.2"
cortex-m-rt = "0.6.11"
cortex-m-semihosting = "0.3.5"
panic-halt = "0.2.0"